version: '3'
services:
  web_sunucum:
    image: ghcr.io/mehmetbayram9000/devops:latest
    container_name: web_sunucum
    restart: always

  nginx_sunucum:
    image: nginx:latest
    container_name: nginx_sunucum
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web_sunucum
    restart: always
